### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.timedelta'

### ISSUE THREAD

**Issue by LanceMcCarthy** [iprak/yahoofinance#28] opened 2021-02-07 21:35 UTC
This used to be working until an update or two ago (it took me a couple weeks to find time to report it).

Using the following config:

```
- platform: yahoofinance
  symbols:
    - AMZN
    - TSLA
    - MSFT
    - AMD
    - GME
```

The integration will not start up due to this error:

```
Logger: homeassistant.setup
Source: custom_components/yahoofinance/__init__.py:72
First occurred: 3:04:11 PM (1 occurrences)
Last logged: 3:04:11 PM

Error during setup of component yahoofinance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/yahoofinance/__init__.py", line 88, in async_setup
    scan_interval = parse_scan_interval(domain_config.get(CONF_SCAN_INTERVAL))
  File "/config/custom_components/yahoofinance/__init__.py", line 72, in parse_scan_interval
    elif scan_interval < MINIMUM_SCAN_INTERVAL:
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.timedelta'
```

**Comment by iprak** [comment] 2021-02-07 21:50
This is a duplicate of https://github.com/iprak/yahoofinance/issues/26.

**Closed by iprak** 2021-02-07 21:50 UTC

**Comment by LanceMcCarthy** [comment] 2021-02-07 22:34
Thanks!

Please add a `Breaking changes` section to your readme, moving from a sensor to an explicit config, is a huge change. This would have prevented me opening the issue (search was not a hit) 😊

**Comment by iprak** [comment] 2021-02-07 23:09
I will do that, this happened in 1.0 release. I had called this out in the release notes but didn't think about adding it to the Readme itself.

**Comment by iprak** [comment] 2021-02-08 01:56
I have added a section about Breaking Changes. Thank you.
