### ISSUE TITLE
yahoo financed down?

### ISSUE THREAD

**Issue by jpoeppelman1** [iprak/yahoofinance#94] opened 2023-04-19 20:05 UTC
Today I started to see this error message, it's happening for all queries.

{"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}

**Comment by Sharknoon** [comment] 2023-04-19 20:22
Same here `Received status 401 for https://query1.finance.yahoo.com/v7/finance/quote?symbols=DTG.DE,P911.DE`

**Comment by jpoeppelman1** [comment] 2023-04-19 20:31
is an API key required and does it need to be refreshed?

**Comment by iprak** [comment] 2023-04-19 20:32
There is no API key. This is a duplicate of https://github.com/iprak/yahoofinance/issues/93.

**Closed by iprak** 2023-04-19 20:32 UTC
